import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs';
import weatherWallpaper from '../public/assets/weather-wallpaper.png';
import Weather from '../components/Weather';
import Spinner from '../components/Spinner';

export default function Home() {
  const [city, setCity] = useState('');
  const [weather, setWeather] = useState('');
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true)
    axios.get(url).then((response) => {
      setWeather(response.data)
    })
    setCity('');
    setLoading(false);
  }

  if (loading) {
    return <Spinner />
  } else {
    return (
      <div>
        <Head>
          <title>Weather Next App</title>
          <meta name="description" content="Generated by create next app" />

        </Head>

        {/* overlay */}
        <div className='absolute top-0 right-0 bottom-0 bg-black/40 z-[1]' />
        {/* Background Image */}
        <Image src={weatherWallpaper} alt='main-wallpaper'
          layout='fill'
          className='object-cover' />

        {/* Search */}
        <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 text-black/60 z-10'>
          <form onSubmit={fetchWeather} className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-black text-black/60 rounded-2xl'>
            <div>
              <input
                onChange={(e) => setCity(e.target.value)}
                className='bg-transparent border-none text-black focus:outline-none text-2xl placeholder:text-black/60'
                type='text' placeholder='search city' />
            </div>
            <button onClick={fetchWeather}>
              <BsSearch size={20} />
            </button>
          </form>
        </div>

        {/* weather data */}
        {weather.main && <Weather data={weather} />}
      </div>
    )
  }
}

